# Generated by Django 4.0.5 on 2022-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergy_allergy_drink_drink_image_nutrition_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_g',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
